I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/inventory.rpy", line 2, in script
    python:
  File "game/inventory.rpy", line 3, in <module>
    class Item:
  File "game/inventory.rpy", line 4, in Item
    self.name=name
NameError: name 'name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/inventory.rpy", line 2, in script
    python:
  File "C:\Users\hequin\Documents\renpy\renpy\ast.py", line 806, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\hequin\Documents\renpy\renpy\python.py", line 1461, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/inventory.rpy", line 3, in <module>
    class Item:
  File "game/inventory.rpy", line 4, in Item
    self.name=name
NameError: name 'name' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.99.9.1168
 
